# Generated by Django 2.0.6 on 2018-06-05 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketlist',
            old_name='date_updated',
            new_name='date_modified',
        ),
    ]
